### PR TITLE
No more database update when application restarts hotfix

### PR DESCRIPTION
**Pull request by FokiDoki**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#199`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/199/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/199/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#200`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/200/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/200/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#201`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/201/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/201/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#202`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/202/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/202/

**Review by HukoJlauII — APPROVED** [review]

**Pull request merged**
