### PR TITLE
Fixed bad access to attributes & types

### PR DESCRIPTION
**Pull request by FokiDoki**
Allowed users to get attributes and types

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#114`: Build failed. Merge restricted, please check build log
GitHub pull request #63 of commit 7bfab81601ba040f74eda2476f2ae5397c478d5c, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/114/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/114/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#115`: Build failed. Merge restricted, please check build log
GitHub pull request #63 of commit 7bfab81601ba040f74eda2476f2ae5397c478d5c, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/115/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/115/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#116`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/116/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/116/

**Review by HukoJlauII — APPROVED** [review]

**Pull request merged**
