### PR TITLE
All hotfixes from master merged to dev

### PR DESCRIPTION
**Pull request by FokiDoki**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#292`: Build failed. Merge restricted, please check build log
GitHub pull request #115 of commit 4259c384e416834b362afb036d5fbdf47e909b42, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/292/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/292/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#293`: Build failed. Merge restricted, please check build log
GitHub pull request #115 of commit 79780c4bfcd26b33a16f9e06cff040c254b22cbf, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/293/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/293/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#294`: Build failed. Merge restricted, please check build log
GitHub pull request #115 of commit 1c5696f37fcc6ee5d249dca0a242c610af1e8efd, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/294/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/294/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#295`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/295/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/295/

**Review by SavaStyle — APPROVED** [review]

**Pull request merged**
