### PR TITLE
Added required flags to scheme 

### PR DESCRIPTION
**Pull request by FokiDoki**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#346`: Build failed. Merge restricted, please check build log
GitHub pull request #133 of commit 9ccb89ae126bb2728277b57be8256520dd604647, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/346/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/346/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#350`: Build failed. Merge restricted, please check build log
GitHub pull request #133 of commit e2f1f9cc99136ca74a33474603280a8a9ef8a9fb, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/350/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/350/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#352`: Build failed. Merge restricted, please check build log
GitHub pull request #133 of commit ea252f39f035f01ce428bfc38b979539be141279, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/352/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/352/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#353`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/353/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/353/

**Review by vchumachenko — APPROVED** [review]

**Review by ya-ne-kit — APPROVED** [review]

**Pull request merged**
