### PR TITLE
Merge 2.0 to master

### PR DESCRIPTION
**Pull request by FokiDoki**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins, run ci

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Review by vchumachenko — APPROVED** [review]

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#345`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/345/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/345/

**Pull request merged**
