### PR TITLE
feature/get-organization-doctypes-attributes

### PR DESCRIPTION
**Pull request by vchumachenko**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#19`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/19/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/19/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#366`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/366/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/366/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#20`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/20/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/20/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#21`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/21/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/21/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#369`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/369/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/369/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#371`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/371/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/371/

**Review by ya-ne-kit — APPROVED** [review]

**Pull request merged**
