### PR TITLE
E2E Tests 

### PR DESCRIPTION
**Pull request by FokiDoki**
For info see [README.md](https://github.com/Toolll1/document-flow/blob/E2E/E2E-Integration-Test/README.md)

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#175`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/175/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/175/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#176`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/176/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/176/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#177`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/177/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/177/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#178`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/178/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/178/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#179`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/179/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/179/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#180`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/180/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/180/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#181`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/181/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/181/

**Review by vchumachenko — APPROVED** [review]

**Pull request merged**
