### PR TITLE
Pre-release bug fixes 

### PR DESCRIPTION
**Pull request by FokiDoki**
Added test data
fixed major bugs

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#336`: Build failed. Merge restricted, please check build log
GitHub pull request #130 of commit cb1001f3ba7a0b29ea6192ed0043c1c5c281fd0c, has merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/336/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/336/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#337`: Build failed. Merge restricted, please check build log
GitHub pull request #130 of commit ca102386908995f71cbfeb58c8b4745112232a51, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/337/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/337/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#338`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/338/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/338/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#339`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/339/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/339/

**Review by vchumachenko — APPROVED** [review]

**Pull request merged**
