### PR TITLE
hotfix/403-for-expired-token

### PR DESCRIPTION
**Pull request by vchumachenko**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#23`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/23/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/23/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#376`: Build failed. Merge restricted, please check build log
GitHub pull request #145 of commit 22c868db322fdd3d12e596ba1574a7f7becb2325, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/376/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/376/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#24`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/24/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/24/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#25`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/25/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/25/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#379`: Build failed. Merge restricted, please check build log
GitHub pull request #145 of commit 22c868db322fdd3d12e596ba1574a7f7becb2325, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/379/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/379/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#26`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/26/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/26/

**Review by ya-ne-kit — APPROVED** [review]

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#380`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/380/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/380/

**Pull request merged**
