### PR TITLE
Docker compose fixed pipelines 

### PR DESCRIPTION
**Pull request by FokiDoki**
Added docker-compose for test envoriment 
Added dockerfile for e2e tests 
Added caching for maven in dockerfile
Fixed docker-compose bad config

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#191`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit d1b58e9a8aa335b676e3d88935a8a51780ea6564, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/191/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/191/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#203`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 0515d28938d11d86439884686d5655dd39f25578, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/203/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/203/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#204`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/204/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/204/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#206`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/206/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/206/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#207`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit d2b095be0f18526e02157e51d900b0b39eea9f8f, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/207/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/207/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#208`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit acfba219990d38f04790e4b87404a8b1bdb82dfa, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/208/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/208/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#209`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit acfba219990d38f04790e4b87404a8b1bdb82dfa, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/209/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/209/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#211`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/211/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/211/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#212`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/212/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/212/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#213`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/213/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/213/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#215`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/215/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/215/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#216`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/216/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/216/

**Comment by FokiDoki** [comment]
> Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#217`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/217/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/217/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#218`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/218/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/218/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#219`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/219/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/219/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#220`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/220/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/220/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#221`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/221/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/221/

**Comment by FokiDoki** [comment]
Jenkins, run CI

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#222`: Build failed. Merge restricted, please check build log
GitHub pull request #95 of commit 4bc03412b32cdfe730666b832bda0745bc47dbde, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/222/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/222/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#223`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/223/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/223/

**Review by SavaStyle — APPROVED** [review]

**Pull request merged**
