### PR TITLE
Added required flags to scheme 

### PR DESCRIPTION
**Pull request by FokiDoki**

### CODE REVIEW

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#10`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/10/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/10/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#347`: Build failed. Merge restricted, please check build log
GitHub pull request #134 of commit 9ccb89ae126bb2728277b57be8256520dd604647, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/347/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/347/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#349`: Build failed. Merge restricted, please check build log
GitHub pull request #134 of commit e2f1f9cc99136ca74a33474603280a8a9ef8a9fb, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/349/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/349/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#11`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/11/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/11/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#12`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/12/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/12/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#351`: Build failed. Merge restricted, please check build log
GitHub pull request #134 of commit ea252f39f035f01ce428bfc38b979539be141279, no merge conflicts.

Details: https://jenkins.fokidoki.su:8888/job/docflow/351/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/351/

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#13`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow-master-no-e2e/13/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow-master-no-e2e/detail/docflow-master-no-e2e/13/

**Review by ya-ne-kit — APPROVED** [review]

**Comment by FokiDoki** [comment]
Jenkins CI/CD: Build `#354`: Build success. Merge approved  

Details: https://jenkins.fokidoki.su:8888/job/docflow/354/
Blue ocean: https://jenkins.fokidoki.su:8888/blue/organizations/jenkins/docflow/detail/docflow/354/

**Pull request merged**
